apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: "{{ .Values.api_service_account_name }}"
      containers:
        - name: api
          image: "ghcr.io/lucaspickering/beta-spray-api:{{ .Values.version_sha }}"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
          env:
            - name: BETA_SPRAY_HOSTNAME
              value: "{{ .Values.hostname }}"
            - name: BETA_SPRAY_DB_HOST
              value: db
            - name: BETA_SPRAY_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: database
            - name: BETA_SPRAY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: username
            - name: BETA_SPRAY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: password
            - name: BETA_SPRAY_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret-key
                  key: secret-key
            - name: BETA_SPRAY_MEDIA_BUCKET
              value: "{{ .Values.media_bucket }}"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.api_service_account_name }}"
  annotations:
    # Link to GCP SA
    iam.gke.io/gcp-service-account: "{{ .Values.api_service_account_email }}"
automountServiceAccountToken: false
