apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: api-gcp-key
          secret:
            secretName: api-gcp-key
      containers:
        - name: api
          image: "ghcr.io/lucaspickering/beta-spray-api:{{ .Values.versionSha }}"
          command:
            - ./scripts/cmd_prd.sh
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
          env:
            - name: BETA_SPRAY_HOSTNAME
              value: "{{ .Values.hostname }}"
            - name: BETA_SPRAY_DB_HOST
              value: db
            - name: BETA_SPRAY_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: database
            - name: BETA_SPRAY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: username
            - name: BETA_SPRAY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: password
            - name: BETA_SPRAY_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret-key
                  key: secret-key
            - name: BETA_SPRAY_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-oauth-client
                  key: id
            - name: BETA_SPRAY_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-oauth-client
                  key: secret
            # Backup is done by a job but we need this for restoring
            - name: BETA_SPRAY_BACKUP_BUCKET
              value: "{{ .Values.databaseBackupBucket }}"
            - name: BETA_SPRAY_MEDIA_BUCKET
              value: "{{ .Values.mediaBucket }}"
            # https://django-storages.readthedocs.io/en/latest/backends/gcloud.html#authentication
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/api-gcp-key/secret-key"
          ports:
            - containerPort: 8000
          volumeMounts:
            # Mount secret as a file, that's how the GCP python lib wants it
            - name: api-gcp-key
              mountPath: "/secrets/api-gcp-key"
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: api
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: api
