apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
  namespace: "{{ .Release.Namespace }}"
spec:
  # Every 6 hours
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: secret-volume
              secret:
                secretName: backup-gcp-key
                items:
                  - key: secret-key
                    path: backup-gcp-key
          containers:
            - name: backup
              image: "ghcr.io/lucaspickering/beta-spray-api:{{ .Values.versionSha }}"
              command:
                - ./scripts/backup.sh
              resources:
                requests:
                  cpu: 5m
                  memory: 20Mi
              volumeMounts:
                - name: secret-volume
                  mountPath: /secrets/
                  readOnly: true
              env:
                - name: BETA_SPRAY_DB_HOST
                  value: db
                - name: BETA_SPRAY_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: database-creds
                      key: database
                - name: BETA_SPRAY_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: database-creds
                      key: username
                - name: BETA_SPRAY_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: database-creds
                      key: password
                # We don't need a real secret key since this pod won't serve requests
                - name: BETA_SPRAY_SECRET_KEY
                  value: placeholder
                - name: BETA_SPRAY_BACKUP_BUCKET
                  value: "{{ .Values.databaseBackupBucket }}"
                - name: BETA_SPRAY_MEDIA_BUCKET
                  value: "{{ .Values.mediaBucket }}"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/backup-gcp-key
