apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    app: db
spec:
  serviceName: db
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:14-alpine
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
              ephemeral-storage: 100Mi
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
              subPath: data
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: password
          ports:
            - containerPort: 5432
  # Request GCE persistent disk
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: db
