# TODO set up encryption and RBAC for secrets https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: api-gcp-key
type: generic
data:
  # This one is already b64 encoded
  secret-key: "{{ .Values.apiGcpKey }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret-key
type: generic
data:
  secret-key: "{{ .Values.apiSecretKey | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
type: generic
data:
  database: "{{ "beta_spray" | b64enc }}"
  username: "{{ "beta_spray" | b64enc }}"
  password: "{{ .Values.databasePassword | b64enc }}"
