apiVersion: v1
kind: Secret
metadata:
  name: database-creds
type: generic
data:
  database: "{{ "beta_spray" | b64enc }}"
  username: "{{ "beta_spray" | b64enc }}"
  password: "{{ .Values.databasePassword | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret-key
type: generic
data:
  secret-key: "{{ .Values.apiSecretKey | b64enc }}"
