version: "3"

services:
  api:
    build: ./api/
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app:rw

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=beta_spray
      - POSTGRES_USER=beta_spray
      - POSTGRES_PASSWORD=beta_spray
