# Generated by Django 4.0.2 on 2022-02-24 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beta',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BoulderImage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('position_x', models.FloatField(help_text='Left-to-right position of the hold within the image, 0-1')),
                ('position_y', models.FloatField(help_text='Top-to-bottom position of the hold within the image, 0-1')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='core.boulderimage')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('holds', models.ManyToManyField(to='core.Hold')),
            ],
        ),
        migrations.CreateModel(
            name='BetaHold',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('body_part', models.CharField(choices=[('LH', 'Left Hand'), ('RH', 'Right Hand'), ('LF', 'Left Foot'), ('RF', 'Right Foot')], help_text='Body part to put on this hold', max_length=2)),
                ('beta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beta')),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hold')),
            ],
        ),
        migrations.AddField(
            model_name='beta',
            name='holds',
            field=models.ManyToManyField(through='core.BetaHold', to='core.Hold'),
        ),
        migrations.AddField(
            model_name='beta',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.problem'),
        ),
    ]
