# Generated by Django 4.0.2 on 2022-03-02 23:21

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoulderImage',
            fields=[
                ('id', core.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', core.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_x', models.FloatField(help_text='Left-to-right position of the hold within the image, 0-1')),
                ('position_y', models.FloatField(help_text='Top-to-bottom position of the hold within the image, 0-1')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='core.boulderimage')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', core.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holds', models.ManyToManyField(blank=True, related_name='problems', to='core.Hold')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='core.boulderimage')),
            ],
        ),
        migrations.CreateModel(
            name='Beta',
            fields=[
                ('id', core.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betas', to='core.problem')),
            ],
        ),
        migrations.CreateModel(
            name='BetaMove',
            fields=[
                ('id', core.models.UUIDPrimaryKeyField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Ordering number of the hold in the beta, with 0 as start')),
                ('body_part', models.CharField(choices=[('LH', 'Left Hand'), ('RH', 'Right Hand'), ('LF', 'Left Foot'), ('RF', 'Right Foot')], help_text='Body part in question', max_length=2)),
                ('beta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='core.beta')),
                ('hold', models.ForeignKey(help_text='Optional destination hold for this move', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hold')),
            ],
            options={
                'unique_together': {('beta', 'order')},
            },
        ),
    ]
