# Generated by Django 4.0.3 on 2022-03-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boulderimage",
            name="name",
            field=models.TextField(default="boulder image"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="beta",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="problem",
            name="name",
            field=models.TextField(),
        ),
    ]
