# Generated by Django 4.0.3 on 2022-05-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_boulderimage_name_alter_beta_name_alter_problem_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BoulderImage",
            new_name="Boulder",
        ),
        migrations.RenameField(
            model_name="hold",
            old_name="image",
            new_name="boulder",
        ),
        migrations.RenameField(
            model_name="problem",
            old_name="image",
            new_name="boulder",
        ),
        migrations.AlterField(
            model_name="hold",
            name="source",
            field=models.CharField(
                choices=[("user", "User"), ("auto", "Auto")],
                help_text="Source of this boulder-hold attribution"
                " (auto or manual)",
                max_length=4,
            ),
        ),
    ]
