# Generated by Django 4.0.3 on 2022-05-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_boulderimage_boulder_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="betamove",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="problem",
            options={"ordering": ["-created_at"]},
        ),
    ]
