# Generated by Django 4.0.3 on 2022-06-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_betamove_options_alter_problem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betamove",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="Ordering number of the hold in the beta, with 0 as"
                " start",
            ),
        ),
    ]
