# Generated by Django 4.0.3 on 2022-06-05 13:17

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import F


def increment_orders(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    # We're bumping order to be 1-indexed, so increment all existing values
    BetaMove = apps.get_model("core", "BetaMove")
    BetaMove.objects.update(order=F("order") + 1)


def decrement_orders(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    # Roll back by decrementing everything
    BetaMove = apps.get_model("core", "BetaMove")
    BetaMove.objects.update(order=F("order") - 1)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_betamove_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betamove",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="Ordering number of the hold in the beta, starting at"
                " 1",
            ),
        ),
        migrations.RunPython(increment_orders, decrement_orders),
    ]
