# Generated by Django 4.0.3 on 2022-06-10 13:13

from django.db import migrations, models

import core.util


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_betamove_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beta",
            name="name",
            field=models.TextField(default=core.util.random_beta_name),
        ),
        migrations.AlterField(
            model_name="problem",
            name="name",
            field=models.TextField(default=core.util.random_problem_name),
        ),
    ]
