# Generated by Django 4.0.3 on 2022-06-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_beta_name_alter_problem_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="betamove",
            name="annotation",
            field=models.TextField(
                blank=True,
                help_text="Free-form annotations created by the user",
            ),
        ),
    ]
