# Generated by Django 4.0.3 on 2022-08-29 04:29

import django.db.models.deletion
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

import core.fields


def to_combined_position(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """
    Map the two separate position columns into a single stringified one
    """
    Hold = apps.get_model("core", "Hold")
    for hold in Hold.objects.all():
        hold.position = core.fields.BoulderPosition(
            hold.position_x, hold.position_y
        )
        hold.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_betamove_annotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="betamove",
            name="position",
            field=core.fields.BoulderPositionField(
                help_text="Position of the move, if not attached to a hold."
                " Mutually exclusive with `hold`.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hold",
            name="position",
            field=core.fields.BoulderPositionField(
                default=core.fields.BoulderPosition(0.0, 0.0),
                help_text="Position of the hold within the boulder image",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="betamove",
            name="hold",
            field=models.ForeignKey(
                help_text="Destination hold for this move."
                " Mutually exclusive with `position`.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hold",
            ),
        ),
        # WARNING: This migration is non-reversible because we're removing
        # non-nullable fields. We could hypothetically make it reversible by
        # adding a default to the fields before removing them, but seems like
        # more effort than it's worth
        migrations.RunPython(to_combined_position),
        migrations.RemoveField(
            model_name="hold",
            name="position_x",
        ),
        migrations.RemoveField(
            model_name="hold",
            name="position_y",
        ),
    ]
