# Generated by Django 4.1.2 on 2023-01-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_problem_external_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="hold",
            name="annotation",
            field=models.TextField(
                blank=True,
                help_text="Free-form annotations created by the user",
            ),
        ),
    ]
