# Generated by Django 4.1.2 on 2023-02-06 11:29

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_hold_annotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betamove",
            name="order",
            field=core.fields.MoveOrderField(
                db_index=True,
                help_text="Ordering number of the hold in the beta,"
                " starting at 1",
            ),
        ),
    ]
