# Generated by Django 4.1.7 on 2023-03-04 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_betamove_is_start_alter_betamove_hold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beta",
            name="owner",
            field=models.ForeignKey(
                # Admin owns everything, by default
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="problem",
            name="owner",
            field=models.ForeignKey(
                # Admin owns everything, by default
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="problem",
            name="visibility",
            field=models.TextField(
                choices=[
                    ("private", "Private"),
                    ("unlisted", "Unlisted"),
                    ("public", "Public"),
                ],
                default="public",
                help_text="Access level for other users to this problem",
            ),
        ),
    ]
