# Generated by Django 4.1.7 on 2023-03-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_beta_owner_problem_owner_problem_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="visibility",
            field=models.TextField(
                choices=[("unlisted", "Unlisted"), ("public", "Public")],
                default="public",
                help_text="Access level for other users to this problem",
            ),
        ),
    ]
