# Generated by Django 4.2.3 on 2023-07-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_hold_boulder_remove_problem_holds_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="betamove",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("hold_id__isnull", True),
                    ("position__isnull", True),
                    _connector="XOR",
                ),
                name="hold_position_mutually_exclusive",
            ),
        ),
    ]
