//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "beta_move")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub order: i32,
    pub body_part: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub beta_id: i64,
    pub hold_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::beta::Entity",
        from = "Column::BetaId",
        to = "super::beta::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CoreBeta,
    #[sea_orm(
        belongs_to = "super::hold::Entity",
        from = "Column::HoldId",
        to = "super::hold::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CoreHold,
}

impl Related<super::beta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreBeta.def()
    }
}

impl Related<super::hold::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreHold.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
