//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "beta")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub problem_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::problem::Entity",
        from = "Column::ProblemId",
        to = "super::problem::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CoreProblem,
    #[sea_orm(has_many = "super::beta_move::Entity")]
    CoreBetamove,
}

impl Related<super::problem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreProblem.def()
    }
}

impl Related<super::beta_move::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreBetamove.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
