//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "hold")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub position_x: f64,
    pub position_y: f64,
    pub source: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub boulder_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::boulder::Entity",
        from = "Column::BoulderId",
        to = "super::boulder::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CoreBoulder,
    #[sea_orm(has_many = "super::beta_move::Entity")]
    CoreBetamove,
    #[sea_orm(has_many = "super::problem_hold::Entity")]
    CoreProblemhold,
}

impl Related<super::boulder::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreBoulder.def()
    }
}

impl Related<super::beta_move::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreBetamove.def()
    }
}

impl Related<super::problem_hold::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreProblemhold.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
