//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::beta::Entity as Beta;
pub use super::beta_move::Entity as BetaMove;
pub use super::boulder::Entity as Boulder;
pub use super::hold::Entity as Hold;
pub use super::problem::Entity as Problem;
pub use super::problem_hold::Entity as ProblemHold;
