//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "problem_hold")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub source: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub hold_id: i64,
    pub problem_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hold::Entity",
        from = "Column::HoldId",
        to = "super::hold::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CoreHold,
    #[sea_orm(
        belongs_to = "super::problem::Entity",
        from = "Column::ProblemId",
        to = "super::problem::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CoreProblem,
}

impl Related<super::hold::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreHold.def()
    }
}

impl Related<super::problem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CoreProblem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
