import { SvgIcon, SvgIconProps } from "@mui/material";
import React from "react";
import { assertUnreachable } from "util/func";
import { BodyPart } from "util/svg";

export const IconLogo: React.FC<SvgIconProps> = (props) => (
  <SvgIcon viewBox="0 0 100 100" {...props}>
    <circle cx="20" cy="82" r="12" />
    <circle cx="74" cy="60" r="12" />
    <circle cx="38" cy="18" r="12" />
    <line strokeWidth="7" x1="20" y1="82" x2="74" y2="60" />
    <line strokeWidth="7" x1="74" y1="60" x2="38" y2="18" />
  </SvgIcon>
);

/**
 * Get the move icon (raw SVG, not MUI icon) corresponding to a body part
 */
export const IconBodyPartRaw: React.FC<
  { bodyPart: BodyPart } & React.SVGProps<SVGPathElement>
> = ({ bodyPart, ...rest }) => {
  switch (bodyPart) {
    case "LEFT_HAND":
      return <IconTriangleRaw transform="rotate(-45)" {...rest} />;
    case "RIGHT_HAND":
      return <IconTriangleRaw transform="rotate(45)" {...rest} />;
    case "LEFT_FOOT":
      return <IconOvalRaw transform="rotate(45)" {...rest} />;
    case "RIGHT_FOOT":
      return <IconOvalRaw transform="rotate(-45)" {...rest} />;
    // NOTE: Don't use default, to force a type error if a variant is added
    case "%future added value":
      assertUnreachable();
  }
};

/**
 * Get the move icon (MUI, not raw SVG) for a particular body part
 */
export const IconBodyPart: React.FC<{ bodyPart: BodyPart } & SvgIconProps> = ({
  bodyPart,
  ...rest
}) => (
  // TODO viewbox
  <SvgIcon viewBox="-3 -3 6 6" {...rest}>
    <IconBodyPartRaw bodyPart={bodyPart} />
  </SvgIcon>
);

const IconTriangleRaw: React.FC<React.SVGProps<SVGPathElement>> = (props) => (
  // Generated by polygons.py
  <path
    d="M-0.866,-2.25 A1,1,0,0,1,0.866,-2.25 L2.38,0.376 A1,1,0,0,1,1.52,1.88
      L-1.52,1.88 A1,1,0,0,1,-2.38,0.376 Z"
    strokeWidth={0.5}
    {...props}
  />
);

const IconOvalRaw: React.FC<React.SVGProps<SVGPathElement>> = (props) => (
  // Generated by polygons.py
  <path
    d="M-1.75,-1.25 A1,1,0,0,1,1.75,-1.25 L1.75,1.25 A1,1,0,0,1,-1.75,1.25 Z"
    strokeWidth={0.5}
    {...props}
  />
);

export const IconNotesRaw: React.FC<React.SVGProps<SVGPathElement>> = (
  props
) => (
  <path
    d="M3 18h12v-2H3v2zM3 6v2h18V6H3zm0 7h18v-2H3v2z"
    transform="scale(0.1) translate(-12, -12)"
    {...props}
  />
);
