name: Build & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: Build & Deploy Environment
        type: environment
        required: true

jobs:
  build:
    name: Build
    uses: LucasPickering/beta-spray/.github/workflows/build.yml@master
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
  deploy:
    name: Deploy
    uses: LucasPickering/beta-spray/.github/workflows/deploy.yml@master
    needs:
      - build
    with:
      # Default to production for master push
      environment: ${{ inputs.environment || 'production' }}
    secrets: inherit
