name: Build Production Images

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: "Build & Push Image"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        component: [api, ui]
        include:
          # API needs to be *first*! The UI prod image relies on the API one for
          # generating Django static assets
          - component: api
            context: ./api
            dockerfile: ./api/prd.Dockerfile
          - component: ui
            context: ./
            dockerfile: ./ui/prd.Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          tags: ghcr.io/lucaspickering/beta-spray-${{ matrix.component }}:latest
          pull: true
          push: ${{ github.ref == 'refs/heads/master' }}
