name: Build Production Images/Assets

on:
  push:
    branches:
      - master
      - deployment
  pull_request:

jobs:
  build-api:
    name: "Build & Push API Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v2
        with:
          context: ./api/
          file: ./api/prd.Dockerfile
          tags: ghcr.io/lucaspickering/beta-spray-api:latest
          pull: true
          # Any of the special branches listed above should trigger a push here
          push: ${{ github.event_name == 'push' }}

      - name: Build static assets
        run: docker run -v $PWD/static:/app/src/static ghcr.io/lucaspickering/beta-spray-api:latest ./m.sh collectstatic

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-static-assets
          path: ./static/

  build-ui:
    name: "Build UI static assets"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Cache npm files
        uses: actions/cache@v2
        with:
          path: ui/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('ui/package-lock.json') }}

      - name: Install dependencies
        working-directory: ui/
        run: npm install

      - name: Build
        working-directory: ui/
        run: NODE_ENV=production npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ui-static-assets
          path: ./ui/build/
