name: Lint & Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # This runs in a docker container
  check-api:
    name: "Lint API"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build Docker Image
        run: docker-compose build api

      - name: Install Dependencies
        run: docker-compose run api poetry install

      - name: Install Dependencies
        run: docker-compose run api poetry install

      - name: Lint
        run: docker-compose run api flake8

      # Make sure there are no uncommited changes to API schema
      - name: Check Schema
        run: >
          docker-compose run api bash -c '
            ./m.sh graphql_schema
            git diff --exit code
          '

      - name: Test
        run: docker-compose run api ./m.sh test

  # This runs natively cause it's faster
  check-ui:
    name: "Lint & Test UI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Cache npm files
        uses: actions/cache@v2
        with:
          path: ui/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('ui/package-lock.json') }}

      - name: Install Dependencies
        working-directory: ui/
        run: npm install

      - name: Type Check
        working-directory: ui/
        run: npm run type-check

      - name: Lint
        working-directory: ui/
        run: npm run lint

      - name: Test
        working-directory: ui/
        run: npm run test
