name: Lint & Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # This runs in a docker container
  check-api:
    name: "Lint API"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build Docker Image
        run: docker-compose build api

      - name: Lint
        run: docker-compose run api poetry run flake8

      - name: Check for GraphQL schema changes
        run: |-
          docker-compose run api ./m.sh graphql_schema
          git diff --exit-code

      - name: Check for DB schema changes
        run: docker-compose run api ./m.sh makemigrations --dry-run --check

      - name: Run Tests
        run: docker-compose run api ./m.sh test

  # This runs natively cause it's faster
  check-ui:
    name: "Lint & Test UI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Cache npm files
        uses: actions/cache@v2
        with:
          path: ui/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('ui/package-lock.json') }}

      - name: Install Dependencies
        working-directory: ui/
        run: npm install

      - name: Type Check
        working-directory: ui/
        run: npm run type-check

      - name: Lint
        working-directory: ui/
        run: npm run lint

      - name: Test
        working-directory: ui/
        run: npm run test
