"""
Django settings for beta_spray project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "dbbackup",
    "debug_toolbar",  # Disabled in prod via INTERNAL_IPS
    "strawberry.django",
    "strawberry_django_plus",
    "guest_user",
    "core",
]

MIDDLEWARE = [
    "strawberry_django_plus.middlewares.debug_toolbar.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Uncomment to test UI loading state
    # "core.middleware.TimeDelayMiddleware",
]

ROOT_URLCONF = "beta_spray.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "beta_spray.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("BETA_SPRAY_DB_NAME", "beta_spray"),
        "USER": os.getenv("BETA_SPRAY_DB_USER"),
        "PASSWORD": os.getenv("BETA_SPRAY_DB_PASSWORD"),
        "HOST": os.getenv("BETA_SPRAY_DB_HOST", "db"),
        "PORT": 5432,
        "ATOMIC_REQUESTS": True,
    }
}

# TODO encrypt backups
# https://django-dbbackup.readthedocs.io/en/master/configuration.html#encrypting-your-backups
DBBACKUP_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
DBBACKUP_STORAGE_OPTIONS = {
    "bucket_name": os.getenv("BETA_SPRAY_BACKUP_BUCKET"),
    "blob_chunk_size": 1024 * 1024,
    # Needed to override the default ACL from the media bucket
    "default_acl": None,
}
DBBACKUP_FILENAME_TEMPLATE = "backup-db-{databasename}-{datetime}.{extension}"
DBBACKUP_MEDIA_FILENAME_TEMPLATE = "backup-media-{datetime}.{extension}"
# 3 days worth of history
DBBACKUP_CLEANUP_KEEP = 12
DBBACKUP_CLEANUP_KEEP_MEDIA = 12

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "guest_user.backends.GuestBackend",
]

GUEST_USER_NAME_GENERATOR = "guest_user.functions.generate_friendly_username"


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Home-rolled field, we'll export the schema to this path on every startup
GRAPHQL_SCHEMA_PATH = "./schema.graphql"

APPEND_SLASH = False

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        }
    },
    "formatters": {
        "simple": {
            "format": "{levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django.request": {
            "level": "DEBUG",
            "handlers": ["console"],
        },
        "django.server": {
            "level": "INFO",
            "handlers": ["console"],
        },
        "django.db.backends": {
            # Set to DEBUG to log DB queries
            "level": "INFO",
            "handlers": ["console"],
            "propagate": False,  # Prevent dupe logging
        },
    },
    "root": {"level": "INFO", "handlers": ["console"]},
}


# Media storage - if GCS bucket is set, use that, otherwise use local
GS_BUCKET_NAME = os.environ.get("BETA_SPRAY_MEDIA_BUCKET")
if GS_BUCKET_NAME:
    # NOTE - For dev, you'll need to pass a creds JSON file into the container
    # and set an env var GOOGLE_APPLICATION_CREDENTIALS to its path
    DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
    # See https://django-storages.readthedocs.io/en/latest/backends/gcloud.html
    GS_DEFAULT_ACL = "publicRead"  # Use unsigned URLs for public access
